import { Router, type IRouter } from "express";
import uploadRouter from "./upload";
import healthRouter from "./health";
import authRouter from "./auth";
import branchesRouter from "./branches";
import rolesRouter from "./roles";
import usersRouter from "./users";
import contactsRouter from "./contacts";
import catalogRouter from "./catalog";
import stockRouter from "./stock";
import purchasesRouter from "./purchases";
import recipesRouter from "./recipes";
import productionRouter from "./production";
import salesRouter from "./sales";
import posRouter from "./pos";
import transfersRouter from "./transfers";
import adjustmentsRouter from "./adjustments";
import expensesRouter from "./expenses";
import reportsRouter from "./reports";
import settingsRouter from "./settings";
import dashboardRouter from "./dashboard";
import storageRouter from "./storage";
import attachmentsRouter from "./attachments";
import receivablesRouter from "./receivables";
import exportsRouter from "./exports";
import returnsRouter from "./returns";
import walletRouter from "./wallet";
import notificationsRouter from "./notifications";
import analyticsPosRouter from "./analytics-pos";
import analyticsPurchasesRouter from "./analytics-purchases";
import analyticsProductionRouter from "./analytics-production";
import analyticsSalesRouter from "./analytics-sales";
import dashboardExecutiveRouter from "./dashboard-executive";
import loyaltyRouter from "./loyalty";
import treasuryRouter from "./treasury";
import purchaseReturnsRouter from "./purchase-returns";
import catalogImportRouter from "./catalog-import";
import replenishmentRouter from "./replenishment";
import internalConsumptionsRouter from "./internal-consumptions";
import receptionsRouter from "./receptions";
import { workersHRRouter } from "./workersHR";
import workersRouter from "./workers";
import preparationOrdersRouter from "./preparation-orders";
import analyticsSellersRouter from "./analytics-sellers";
import crmRouter from "./crm";
import intelligenceRouter from "./intelligence";
import aiControlRouter from "./ai-control";
import checklistRouter from "./checklist";
import pushRouter from "./push";
import notificationSettingsRouter from "./notification-settings";

const router: IRouter = Router();

router.use(uploadRouter);
router.use(healthRouter);
router.use(authRouter);
router.use(branchesRouter);
router.use(rolesRouter);
router.use(usersRouter);
router.use(contactsRouter);
router.use(catalogRouter);
router.use(stockRouter);
router.use(purchasesRouter);
router.use(recipesRouter);
router.use(productionRouter);
router.use(salesRouter);
router.use(posRouter);
router.use(transfersRouter);
router.use(adjustmentsRouter);
router.use(expensesRouter);
router.use(reportsRouter);
router.use(settingsRouter);
router.use(dashboardRouter);
router.use(storageRouter);
router.use(attachmentsRouter);
router.use(receivablesRouter);
router.use(exportsRouter);
router.use(returnsRouter);
router.use(walletRouter);
router.use(notificationsRouter);
router.use(analyticsPosRouter);
router.use("/analytics/purchases", analyticsPurchasesRouter);
router.use("/analytics/production", analyticsProductionRouter);
router.use("/analytics/sales", analyticsSalesRouter);
router.use("/dashboard/executive", dashboardExecutiveRouter);
router.use("/loyalty", loyaltyRouter);
router.get("/export/loyalty-customers", (req, res) => { res.redirect(307, `/api/loyalty/export/loyalty-customers?${new URLSearchParams(req.query as any).toString()}`); });
router.use(treasuryRouter);
router.use(purchaseReturnsRouter);
router.use(catalogImportRouter);
router.use(replenishmentRouter);
router.use(internalConsumptionsRouter);
router.use(receptionsRouter);
// HR routes MUST be registered before workersRouter to avoid :id wildcard conflicts
router.use(workersHRRouter);
router.use(workersRouter);
router.use(preparationOrdersRouter);
router.use(analyticsSellersRouter);
router.use("/crm", crmRouter);
router.use(intelligenceRouter);
router.use(aiControlRouter);
router.use(checklistRouter);
router.use(pushRouter);
router.use(notificationSettingsRouter);

export default router;
