kind = "web"
previewPath = "/"
title = "Pacane ERP"
version = "1.0.0"
id = "artifacts/erp-app"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23023

[services.env]
PORT = "23023"
BASE_PATH = "/"

[services.development]
run = "pnpm --filter @workspace/erp-app run dev"
